# -*- coding: utf-8 -*-
"""
Created on Tue Nov  1 20:03:33 2022

@author: Alexandre Siqueira de Medeiros
@contact: alexandre.siqueira@gmailcom
"""

PERIODS_INDICATORS = [5, 10, 20, 50, 200]
PERIODS_RESULTS = [3, 5, 7, 14, 20]
TRAIN_TEST_SPLIT_SIZES = [0.15, 0.2, 0.3]
ALGORITMS = ["SVM", "LREG", "DTC3", "DTC6", "GNB", "KNN", "RFC"]
NORMALIZE_OPTIONS = [True, False]

STOCKS = ["PETR4","VALE3","ITUB4","BBDC4","BOVA11","BBAS3","PETR3","MGLU3","ITSA4","GGBR4",
           "JBSS3","BRFS3","LREN3","CIEL3","CSNA3","USIM5","RENT3","CCRO3","WEGE3","UGPA3",
           "LAME4","CMIG4","BRML3","ELET3","RADL3","EQTL3","CSAN3","SBSP3","EMBR3","HYPE3",
           "GOLL4","GOAU4","BBDC3","CYRE3","BRKM5","BRAP4","MULT3","QUAL3","SANB11","MRFG3",
           "MRVE3","ELET6","TOTS3","SULA11","CPFE3","CPLE6","ENBR3","CESP6","ECOR3","BEEF3","PSSA3"]

BY_CRITERIA_RANK = ["SCO_TEST", "VALID_BAL_PRED", "SCO_VALID"]
DATA_YEAR_INIT=2012
DATA_YEAR_END=2023
DATA_TRAIN_DATE_INIT=20170101
DATA_TRAIN_DATE_END=20220101

DEFAULT_INIT_BALANCE=10000
ROOT_PATH="D:/data/b3/"
DATA_PATH=ROOT_PATH
DATA_PATH_RESULTS=DATA_PATH+"results/"
DATA_PATH_STOCKS=DATA_PATH+"timeseries/day/sup/"
DATA_PATH_SERIES=DATA_PATH+"series/"
DATA_PATH_COMPANIES=DATA_PATH+"companies/"
MODEL_PATH=ROOT_PATH+"model/"

CSV_SEPARATOR = ';'
FILE_NAME_RESULTADO = '-resultado.csv'
DEFAULT_PERIOD_IND=20
DEFAULT_PERIOD_RES=7
DEFAULT_NORMALIZED=False
DEFAULT_TEST_SIZE=0.2

DATA_URL_DOWNLOAD_B3=""
#urls base64 para json sobre proventos dos ativos
URL_COMPANY_DETAIL=""
URL_COMPANY_SUPPLEMENT=""
URL_CASH_DIVIDENDS=""
URL_GET_COMPANIES=""

URL_DOWNLOAD_B3=""
URL_INTRADAY_DOWNLOAD = ""

PATH_B3_INTRADAY_LOCAL = "D:/data/b3/intraday/"
PATH_B3_SERIES_LOCAL = "D:/data/b3/series/"
PATH_B3_TIMESERIES_DAY = "D:/data/b3/timeseries/day/sup/"
FILE_INTRADAY_PREFIX = "TradeIntraday_"
TIMEFRAMES = [1, 2, 5, 15, 30]

GENERATE_TREE_GRAPH = False

